# Generated by Django 5.1.3 on 2025-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_spaces', models.IntegerField(default=500)),
                ('min_hourly_spaces', models.IntegerField(default=50)),
                ('occupancy_requirement', models.FloatField(default=0.85)),
                ('hourly_revenue', models.FloatField(default=15.0)),
                ('monthly_revenue', models.FloatField(default=10.0)),
                ('corporate_revenue', models.FloatField(default=20.0)),
                ('hourly_reliability', models.FloatField(default=0.75)),
                ('monthly_reliability', models.FloatField(default=0.9)),
                ('corporate_reliability', models.FloatField(default=0.6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hourly_spaces', models.IntegerField(blank=True, null=True)),
                ('monthly_spaces', models.IntegerField(blank=True, null=True)),
                ('corporate_spaces', models.IntegerField(blank=True, null=True)),
                ('expected_revenue', models.FloatField(blank=True, null=True)),
                ('expected_occupancy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
